[Fix] Multiple calls to client.Close causes panic
apache/pulsar-client-go pull request #1046
Opened 2023-07-04 03:10 UTC by crossoverJie

Fixes #1026 

### Motivation

Multiple calls to `client.Close` causes panic.

### Modifications

Add `closeOnce sync.Once`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

2023-07-04 03:34 UTC, Shoothzj commented
This PR enables the 'close' method to be re-entrant. However, I'm not quite seeing the value in making the 'close' method re-entrant. Could you provide any scenarios or use cases where this would be necessary?

2023-07-04 03:43 UTC, crossoverJie commented
This is just defensive programming, the consumer's close logic also has similar usage.

https://github.com/apache/pulsar-client-go/blob/5f8df2782251226b63b2dad9f4e87fd4bbd31ef5/pulsar/consumer_multitopic.go#L256-L270

2023-07-04 04:57 UTC, tisonkun approved these changes
Generally looks good.

My concern can be that it may not be an idiom among the code. So if we change the flavor randomly it can introduce noise. But I think this direction is good to go.

2023-07-04 04:58 UTC, tisonkun requested changes
What if we cause the internal closes idempotent instead of hacky wrapping an `Once` outer?

2023-07-04 09:07 UTC, crossoverJie commented
> What if we cause the internal closes idempotent instead of hacky wrapping an `Once` outer?

https://github.com/apache/pulsar/blob/a3bca685a4ef0916462228e035f77fdbf295653d/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java#L735-L739
![image](https://github.com/apache/pulsar-client-go/assets/15684156/804e3ff2-1474-43c0-966d-2715ac5b3c77)


![image](https://github.com/apache/pulsar-client-go/assets/15684156/5ae06aea-0d90-44bd-a567-01e79845ee28)

I looked at the Java SDK's close logic, it uses an internal state to maintain the client state, and the `Once` principle used here is similar.

2023-07-10 10:39 UTC, RobertIndie approved these changes

2023-09-07 09:12 UTC, RobertIndie commented
@tisonkun @Shoothzj  Could you take a look at this? Does the explanation make sense to you?

2023-09-09 15:43 UTC, Shoothzj commented
I believe this modification is feasible. Regardless of whether or not it supports reentrancy, and whether reentrancy supports concurrency, we can maintain consistent behavior across the entire code repository.

2023-09-10 03:43 UTC, tisonkun approved these changes

2023-09-10 03:43 UTC, merged

2023-09-10 03:43 UTC, tisonkun commented
Thanks for your contribution!